image: alpine/edge
artifacts:
  - greedy/dist/greeedy-linux-amd64
  - greedy/dist/greeedy-linux-386
  - greedy/dist/greeedy-linux-arm64
  - greedy/dist/greeedy-windows-amd64.exe
packages:
  - go
sources:
  - https://git.sr.ht/~skuzzymiglet/greedy
tasks:
  - builds: |
      cd greedy
      ./gogo-release
